config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/plots', to: 'plots#index'

  resources :plot_plants, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plots
end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :plot_plants
  has_many :plots, through: :plot_plants
end

app/models/plot.rb
class Plot < ApplicationRecord
  belongs_to :garden
  has_many :plot_plants
  has_many :plants, through: :plot_plants
end

app/models/plot_plant.rb
class PlotPlant < ApplicationRecord
  belongs_to :plot
  belongs_to :plant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plot_plants_controller.rb
class PlotPlantsController < ApplicationController
  def destroy
    require 'pry'; binding.pry
    plot_plant = PlotPlant.find_by(plot_id: params[:id], plant_id: params[:id])
    plot_plant.delete
    redirect_to '/plots'
    ## tried to change the plant_id: params[:everything I could think of]
    ## plant: params[:id]
    ## plant_id: params[plant]
    ## plant_id: params[:plant]
    ## plant_id: params[@plant.id]
    ## plant_id: params[plant.id]
    ## plant_id: params[plant_id]
  end
end

app/controllers/plots_controller.rb
class PlotsController < ApplicationController
  def index
    @plots = Plot.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plots/index.html.erb
<h1>Plots Index Page</h1>

<ul>
  <% @plots.each do |plot| %>
    <li id="plot_info_<%= plot.id %>">
      Plot Number: <%= plot.number %>
      <br/>
      <% plot.plants.each do |plant| %>
        <p><%= plant.name %> <%= link_to "Delete #{plant.name}", plot_plant_path(plot, plant), method: :delete %></p>
      <% end %>
    </li>
  <% end %>
</ul>